[server]
maxUploadSize = 5
runOnSave = false

[theme]
primaryColor = "#6366F1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F7F9"
textColor = "#1E1E1E"
font = "sans serif"

[browser]
gatherUsageStats = false
